### ISSUE TITLE
cmlphp  能否支持下阿里云的ocs/memcached

### ISSUE THREAD

**Issue by qiacoucc** [linhecheng/cmlphp#10]
cmlphp  能否支持下阿里云的ocs/Memcached

**Comment by linhecheng** [comment]
你好，已经支持。

参考官方文档
yum install cyrus-sasl-plain cyrus-sasl cyrus-sasl-devel cyrus-sasl-lib 安装 SASL 相关环境
安装libmemcache并开启支持sals
安装memcached扩展开启支持sals

框架缓存配置:
    'default_cache' => [
        'on' => 1, 
        'driver' => 'Memcache',
        'prefix' => 'bx_',//配置缓存前缀防止冲突
        'server' => [
            [
                'host' => 'xxxxx',
                'port' => '11211',
                'username' => 'usename,
                'password' => 'password'

            ]        
        ],
    ],

**Comment by qiacoucc** [comment]
好的 感谢 原来把Memcached和Memcache合并了  ,建议雨空有空可以录制一些框架的视频教程哦
------------------ Original ------------------
