### ISSUE TITLE
为什么模板引擎不能再精简一些？

### ISSUE THREAD

**Issue by jacochan** [linhecheng/cmlphp#11]
这个框架非常优秀，还在仔细研读作者的框架思维。发现真的很贴近日常开发应对的各类问题。

看到模板引擎用的{{}}双花括号的，为什么不能单花括号{dump($_GET)}来精简呢？

**Comment by linhecheng** [comment]
你好，定界符是可以通过配置来修改的，参考[https://doc.cmlphp.com/devintro/view/cmlengine.html#%E6%A8%A1%E6%9D%BF%E5%AE%9A%E7%95%8C%E7%AC%A6](url)
