### ISSUE TITLE
是否必须使用composer的AUTOLOAD方法？

### ISSUE THREAD

**Issue by dongnanyanhai** [linhecheng/cmlphp#2]
在框架核心文件Cml.php看到一句被注释的代码：
// 注册AUTOLOAD方法
//spl_autoload_register('Cml\Cml::autoload');

而在“cmlphp2.5-demo-proj”项目中，看到使用的是composer目录下的文件来处理autoload。

框架中并无实现独立的Cml::autoload方法，是否需要由开发者自己实现？

**Comment by linhecheng** [comment]
不用的，在加入composer支持之前框架有单独实现了\Cml\Cml::autoload 但是加入composer支持之后就是直接使用composer的加载器了，所以移除了原\Cml\Cml::autoload。不需要再去实现的

**Comment by linhecheng** [comment]
抱歉，刚看到你是问“是否必须使用composer的AUTOLOAD方法？”，你的意思是不想用composer的加载器？。因为其实composer的加载逻辑本身也不是很复杂所以还是建议直接用就好了。这也是我把原来自己实现的\Cml\Cml::autoload移除的原因。一方面是没必要重复，另外一方面是用composer是大趋势。我不敢保证三五年后别人维护现在开发的项目的时候看到没用composer会怎么吐糟，哈哈哈

**Comment by dongnanyanhai** [comment]
@linhecheng 之前用的是CI类似的框架，还没接触过composer，所以看到cmlphp2.5-demo-proj里的composer后有点懵了。采用composer确实不错，看来得再补充composer相关的知识了！

昨天看了cmlphp框架的文档和部分代码后，感觉非常棒，非常容易上手，感谢开源这么“舒服”的框架！
