### ISSUE TITLE
undefined function 错误

### ISSUE THREAD

**Issue by dongnanyanhai** [linhecheng/cmlphp#3]
“cmlphp2.5-demo-proj”项目的文件，放到网站根目录下，在“DefaultController”中增加下面代码，出现Call to undefined function Cml\Http\Request\host()错误！

```php
<?php namespace web\Controller;

use Cml\Controller;
use Cml\Http\Request;

class DefaultController extends Controller
{
    public function index()
    {
        echo '欢迎使用cml框架,应用初始化成功';
        echo \Cml\Http\Request\host();
    }
}
```

测试系统环境是windows10 upupw套件（apache+php）。

不知能能不能提供原先的Cml\Cml::autoload 方法，作为composer之外的一种备选方案！

**Comment by linhecheng** [comment]
应该是  echo \Cml\Http\Request::host();
:: 不是\。host是一个类方法不是函数

**Comment by dongnanyanhai** [comment]
@linhecheng 

好，我直接抄文档这里的。

https://www.zybuluo.com/linhecheng/note/226146#request

**Comment by linhecheng** [comment]
是我的失误，谢谢提醒啦。我更新下文档

**Comment by dongnanyanhai** [comment]
@linhecheng 正在学习这个框架，接下来还会打扰到，希望不要介意！

能自己查资料解决的我一定尽量自己查，实在不好意思，之前对php命名空间相关知识了解不足！

**Comment by linhecheng** [comment]
有问题欢迎找我交流啦，一起交流进步^_^
