### ISSUE TITLE
input 类能否增加一个方法过滤数组内的数据

### ISSUE THREAD

**Issue by dongnanyanhai** [linhecheng/cmlphp#5]
```html
<form>
    <input type="email" name="data[email]" id="email" value="">
<input type="password" name="data[password]" id="password" value="">
</form>
```
当我们在表单里把数据放到一个data数组里时，通过cml的input类无法获取到过滤后的data数组。

**Comment by linhecheng** [comment]
这个问题其实我之前有考虑过，但是因为postInt getInt这些都是强制转成指定类型，而表单data数组却可能是多个字段不同类型，所以就没有加数组的判断。你可以根据需要调用
$data = \Cml\Secure::stripTags($_POST['data']);
$data = \Cml\Secure::htmlspecialchars($_POST['data']);
$data = \Cml\Secure::filterScript($_POST['data']);
等Secure中的方法
