### ISSUE TITLE
静态资源管理 没明白直接在PHP里使用

### ISSUE THREAD

**Issue by muzichenglong** [linhecheng/cmlphp#9]
我下载了你的 cmlphp-demo-background  示例 在debug模式下 静态文件映射正常，但是关闭了debug后 静态文件404了 
然后通过方法1 php index.php symlink 后可以正常映射 ， 求问是否关闭debug后必须 cli 处理映射

**Comment by linhecheng** [comment]
一种是直接执行命令行。另外一种就是直接在控制器方法里执行
\Cml\Tools\StaticResourceStaticResource::createSymbolicLink();
也可以，结果是一样的。这样主要是为了将应用的所有资源隔离。不会说出现我发布上线 controler发布一次要跑到model里又发布一次，又跑到view里发布一次。然后跑到static下发布一次。
通过将每一个小应用隔离掉，发布的时候只要直接把整个应用提交就好了
